In [5]:
my_list = [1,2,3]


In [6]:
my_list

[1, 2, 3]

Importing the Numpy Library

In [7]:
import numpy as np

In [9]:
arr= np.array(my_list)

In [10]:
arr

array([1, 2, 3])

Matrix Representation

In [11]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.
Basically used to generate an array within a given specific interval mentioned 

In [12]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### So in the above example the range mentioned is 0 to 10 which gives 10 numbers from 0 to 9

In [13]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

passing the third argument 2 gives us  even elements or we can say multiples of 2 in the given range 

In [16]:
np.arange(0,11,4)

array([0, 4, 8])

So 4 as third argument gives us multiples of 4

##### zeros and ones
Generate arrays of zeros or ones


In [35]:
np.zeros(3)

array([0., 0., 0.])

the argument of the function tell how many zeroes we want in the array


In [19]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

##### linspace
Return evenly spaced numbers over a specified interval.

In [32]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

    -->SO we an see in the above example we get 3 evenly spaced points between the interval 0 and 10 
    the first two arguments repersent the start and end range and third argument how many numbers we want

In [21]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

    --> here we get 50 numbers evenly distributed in 0 to 10

In [29]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

## eye

Creates an identity matrix

In [30]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random
Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).

In [31]:
np.random.rand(10)

array([0.08610521, 0.63413614, 0.62899204, 0.77365592, 0.97299796,
       0.0413339 , 0.65249231, 0.7489624 , 0.98080482, 0.13110935])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [38]:
np.random.randint(1,100)

79

    -->this gave a single random no in the range 1 to 100

In [39]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [40]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [41]:
ranarr

array([34, 10, 28, 31, 47, 10, 22, 28, 10,  3])

    -->this give us a random array with 10 elemnts in the range 0 to 50

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [43]:
ranarr

array([34, 10, 28, 31, 47, 10, 22, 28, 10,  3])

In [44]:
ranarr.max()

47

    -->This will give us the maximum element and we can do simalrly for min

In [45]:
ranarr.argmax()

4

    -->This will return the posotion of the max elemnt and simalrly the argmin() for min index elemnt

# Broadcasting

#### Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [46]:
#Setting a value with index range (Broadcasting)
#this would set hundred at index 0 to 4 (NOTE:5 is not included)
arr[0:5]=100

#Show
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [48]:
#Important notes on Slices
#this slice would copy elemnts in the slice_of_arr from the original arr from index 0 to 5
slice_of_arr = arr[0:6]

#Show slice
slice_of_arr

array([100, 100, 100, 100, 100,   5])

In [49]:
#Change Slice
#via this we change the value in the array make them 99
slice_of_arr[:]=99

#Show Slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99])

    --> Issue with above code is it changes the value to 99 in the original array arr also 
    check below

In [50]:
arr


array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [51]:
#To get a copy, need to be explicit
#thus for copy purposes we use the copy method 
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend usually using the comma notation for clarity.

In [52]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [53]:
#Indexing row
arr_2d[1]

array([20, 25, 30])

In [55]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0]
#this thing can also be written as arr_2d[1,0]

20

In [56]:
arr_2d[1,0]

20

    --> For Fancy indexing refer the course notes

## Selection
This is selection based or comparison based indexing


In [57]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [58]:
#we will get boolean T or F depending upon the condition mentioned
#Here the condition is greater than 4 so elemnts greater than 4 T will come or else F
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [59]:
bool_arr=arr>5

In [60]:
bool_arr


array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [61]:
#this gives the elements satisfying the condition
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [62]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])